instacar/cars/urls.py
from django.urls import path

from .views import (
    CarListView,
    CarDetailView,
    CarCreateView,
    CarUpdateView,
    CarDeleteView,
    ProfileListView,
    ProfileUpdateView,
    create_comment,
    edit_comment,
    delete_comment
)

app_name = 'car'

urlpatterns = [
    path('', CarListView.as_view(), name='index'),
    path('cars/<int:pk>/', CarDetailView.as_view(), name='car_detail'),
    path('profiles/<str:username>/',
         ProfileListView.as_view(),
         name='profile'
         ),
    path('profile/edit/', ProfileUpdateView.as_view(), name='profile_edit'),
    path('cars/create/', CarCreateView.as_view(), name='car_create'),
    path('cars/<int:pk>/edit/', CarUpdateView.as_view(), name='car_edit'),
    path('cars/<int:pk>/delete/', CarDeleteView.as_view(), name='car_delete'),
    path('cars/<int:car_id>/comments/', create_comment, name='create_comment'),
    path(
        'cars/<int:car_id>/comments/<int:comment_id>/edit/',
        edit_comment,
        name='edit_comment'
    ),
    path(
        'cars/<int:car_id>/comments/<int:comment_id>/delete/',
        delete_comment,
        name='delete_comment'
    ),
]

instacar/instacar/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.edit import CreateView

from cars.forms import ProfileForm

urlpatterns = [
    path('', include('cars.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path(
        'auth/registration/',
        CreateView.as_view(
            template_name='registration/registration_form.html',
            form_class=ProfileForm,
            success_url=reverse_lazy('login')
        ),
        name='registration'
    ),
    path('api/', include('api.v1.urls')),
]

instacar/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

from instacar.constants import EMAIL_MAX_LENGHT


class UserProfile(AbstractUser):
    """Модель Пользователя"""
    email = models.EmailField(max_length=EMAIL_MAX_LENGHT, unique=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = (
        'username',
        'first_name',
        'last_name',
        'password'
    )

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'
        ordering = ('-id',)

    def __str__(self):
        return self.get_full_name()

instacar/api/v1/views/users_views.py
from rest_framework import permissions, viewsets

from api.v1.serializers.user_serializer import UserProfileSerializer
from users.models import UserProfile


class UserViewSet(viewsets.ModelViewSet):
    queryset = UserProfile.objects.all()
    serializer_class = UserProfileSerializer
    http_method_names = ["get", "head", "options"]
    permission_classes = (permissions.IsAdminUser,)

instacar/templates/blog/comment.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block title %}
  {% if '/edit_comment/' in request.path %}
    Редактирование комментария
  {% else %}
    Удаление комментария
  {% endif %}
{% endblock %}
{% block content %}
  {% if user.is_authenticated %}
    <div class="col d-flex justify-content-center">
      <div class="card" style="width: 40rem;">
        <div class="card-header">
          {% if '/edit_comment/' in request.path %}
            Редактирование комментария
          {% else %}
            Удаление комментария
          {% endif %}
        </div>
        <div class="card-body">
          <form method="post"
            {% if '/edit_comment/' in request.path %}
              action="{% url 'car:edit_comment' comment.post_id comment.id %}"
            {% endif %}>
            {% csrf_token %}
            {% if not '/delete_comment/' in request.path %}
              {% bootstrap_form form %}
            {% else %}
              <p>{{ comment.text }}</p>
            {% endif %}
            {% bootstrap_button button_type="submit" content="Отправить" %}
          </form>
        </div>
      </div>
    </div>
  {% endif %}
{% endblock %}

instacar/templates/blog/confirm_delete.html
{% extends "base.html" %}

{% block title %}
  Удаление автомобиля
{% endblock %}

{% block content %}
  <h1>Вы уверены, что хотите удалить этот автомобиль?</h1>
  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Да, удалить</button>
    <a href="{% url 'car:car_detail' object.pk %}" class="btn btn-secondary">Отмена</a>
  </form>
{% endblock %}

instacar/templates/blog/create.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block title %}
  {% if '/edit/' in request.path %}
    Редактирование публикации
  {% elif "/delete/" in request.path %}
    Удаление публикации
  {% else %}
    Добавление публикации
  {% endif %}
{% endblock %}
{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-header">
        {% if '/edit/' in request.path %}
          Редактирование публикации
        {% elif '/delete/' in request.path %}
          Удаление публикации
        {% else %}
          Добавление публикации
        {% endif %}
      </div>
      <div class="card-body">
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {% if not '/delete/' in request.path %}
            {% bootstrap_form form %}
          {% else %}
            <article>
              {% if form.instance.image %}
                <a href="{{ form.instance.image.url }}" target="_blank">
                  <img class="border-3 rounded img-fluid img-thumbnail mb-2" src="{{ form.instance.image.url }}">
                </a>
              {% endif %}
              <p>{{ form.instance.pub_date|date:"d E Y" }} | {% if form.instance.location and form.location.is_published %}{{ form.instance.location.name }}{% else %}Планета Земля{% endif %}<br>
              <h3>{{ form.instance.title }}</h3>
              <p>{{ form.instance.text|linebreaksbr }}</p>
            </article>
          {% endif %}
          {% bootstrap_button button_type="submit" content="Отправить" %}
        </form>
      </div>
    </div>
  </div>
{% endblock %}

instacar/templates/blog/detail.html
{% extends "base.html" %}

{% block title %}
  {{ car.make }}
  {{ car.created_at|date:"d E Y" }}
{% endblock %}

{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-body">
        <h5 class="card-title"> {{ car.make }}, {{car.model}}</h5>
        <h6 class="card-title">Год выпуска:  {{car.year}}</h6>
        <h6 class="card-subtitle mb-2 text-muted">
          <small>
            {{ car.created_at|date:"d E Y, H:i" }}
            От автора
            <a class="text-muted" href="{% url 'car:profile' car.owner.username %}">@{{ car.owner.username }}</a>
          </small>
        </h6>
        <p class="card-text">{{ car.description|linebreaksbr }}</p> <!-- Измените post.text на car.description -->
        {% if user == car.owner %}
          <div class="mb-2">
            <a class="btn btn-sm text-muted" href="{% url 'car:car_edit' car.id %}" role="button">
              Отредактировать публикацию
            </a>
            <a class="btn btn-sm text-muted" href="{% url 'car:car_delete' car.id %}" role="button">
              Удалить публикацию
            </a>
          </div>
        {% endif %}
        {% include "includes/comments.html" %}
      </div>
    </div>
  </div>
{% endblock %}

instacar/templates/blog/index.html
{% extends "base.html" %}
{% block title %}
  Лента записей
{% endblock %}
{% block content %}
  {% for car in page_obj %}
    <article class="mb-5">
      {% include "includes/post_card.html" %}
    </article>
  {% endfor %}
  {% include "includes/paginator.html" %}
{% endblock %}

instacar/templates/blog/profile.html
{% extends "base.html" %}
{% block title %}
  Страница пользователя {{ profile }}
{% endblock %}
{% block content %}
  <h1 class="mb-5 text-center ">Страница пользователя {{ profile.username }}</h1>
  <small>
    <ul class="list-group list-group-horizontal justify-content-center">
      {% if user.is_authenticated and request.user == profile %}
      <a class="btn btn-sm text-muted" href="{% url 'car:profile_edit' %}">Редактировать профиль</a>
      <a class="btn btn-sm text-muted" href="{% url 'password_change' %}">Изменить пароль</a>
      {% endif %}
    </ul>
  </small>
  <br>
  <h3 class="mb-5 text-center">Публикации пользователя</h3>
  {% for car in page_obj %}
    <article class="mb-5">
      {% include "includes/post_card.html" %}
    </article>
  {% endfor %}
  {% include "includes/paginator.html" %}
{% endblock %}

instacar/templates/blog/user.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block title %}
  Редактирование профиля
{% endblock %}
{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-header">
        Редактирование профиля - {{ request.user }}
      </div>
      <div class="card-body">
        <form method="post">
          {% csrf_token %}
          {% bootstrap_form form %}
          {% bootstrap_button button_type="submit" content="Отправить" %}
        </form>
      </div>
    </div>
  </div>
{% endblock %}