instacar/cars/urls.py
from django.urls import path

from .views import (
    CarListView,
    CarDetailView,
    CarCreateView,
    CarUpdateView,
    CarDeleteView,
    ProfileListView,
    ProfileUpdateView,
    create_comment,
    edit_comment,
    delete_comment
)

app_name = 'car'

urlpatterns = [
    path('', CarListView.as_view(), name='index'),
    path('cars/<int:pk>/', CarDetailView.as_view(), name='car_detail'),
    path('profiles/<str:username>/',
         ProfileListView.as_view(),
         name='profile'
         ),
    path('profile/edit/', ProfileUpdateView.as_view(), name='profile_edit'),
    path('cars/create/', CarCreateView.as_view(), name='car_create'),
    path('cars/<int:pk>/edit/', CarUpdateView.as_view(), name='car_edit'),
    path('cars/<int:pk>/delete/', CarDeleteView.as_view(), name='car_delete'),
    path('cars/<int:car_id>/comments/', create_comment, name='create_comment'),
    path(
        'cars/<int:car_id>/comments/<int:comment_id>/edit/',
        edit_comment,
        name='edit_comment'
    ),
    path(
        'cars/<int:car_id>/comments/<int:comment_id>/delete/',
        delete_comment,
        name='delete_comment'
    ),
]

instacar/instacar/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.edit import CreateView

from cars.forms import ProfileForm

urlpatterns = [
    path('', include('cars.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path(
        'auth/registration/',
        CreateView.as_view(
            template_name='registration/registration_form.html',
            form_class=ProfileForm,
            success_url=reverse_lazy('login')
        ),
        name='registration'
    ),
    path('api/', include('api.v1.urls')),
]

instacar/templates/includes/comments.html
{% if user.is_authenticated %}
  {% load django_bootstrap5 %}
  <h5 class="mb-4">Оставить комментарий</h5>
  <form method="post" action="{% url 'car:create_comment' car.id %}">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="Отправить" %}
  </form>
{% endif %}
<br>
{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'car:profile' comment.author.username %}" name="comment_{{ comment.id }}">
          @{{ comment.author.username }}
        </a>
      </h5>
      <small class="text-muted">{{ comment.created_at }}</small>
      <br>
      {{ comment.content|linebreaksbr }}
      </br>
    </div>
    {% if user == comment.author %}
      <a class="btn btn-sm text-muted" href="{% url 'car:edit_comment' car.id comment.id %}" role="button">
        Отредактировать комментарий
      </a>
      <a class="btn btn-sm text-muted" href="{% url 'car:delete_comment' car.id comment.id %}" role="button">
        Удалить комментарий
      </a>
    {% endif %}
  </div>
{% endfor %}

instacar/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© IstaCar</p>
</footer>

instacar/templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'car:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        InstaCar
      </a>
      {% with request.resolver_match.view_name as view_name %}
        <ul class="nav nav-pills">
          {% if user.is_authenticated %}
            <div class="btn-group" role="group" aria-label="Basic outlined example">
              <button type="button" class="btn btn-outline-primary">
                <a class="text-decoration-none text-reset" href="{% url 'car:car_create' %}">Написать пост</a>
              </button>
              <button type="button" class="btn btn-outline-primary">
                <a class="text-decoration-none text-reset" href="{% url 'car:profile' user.username %}">{{ user.username }}</a>
              </button>
              <form action="{% url 'logout' %}" method="post" style="display: inline;">
                  {% csrf_token %}
                  <button type="submit" class="btn btn-outline-primary rounded-end">Выйти</button>
              </form>
            </div>
          {% else %}
            <div class="btn-group" role="group" aria-label="Basic outlined example">
              <button type="button" class="btn btn-outline-primary">
                <a class="text-decoration-none text-reset" href="{% url 'login' %}">Войти</a>
              </button>
              <button type="button" class="btn btn-outline-primary">
                <a class="text-decoration-none text-reset" href="{% url 'registration' %}">Регистрация</a>
              </button>
            </div>
          {% endif %}
        </ul>
      {% endwith %}
    </div>
  </nav>
</header>

instacar/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
  <nav aria-label="Page navigation" class="my-5">
    <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            << </a>
        </li>
      {% endif %}
      {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">
            >>
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
            Последняя
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

instacar/templates/includes/post_card.html
<div class="col d-flex justify-content-center">
  <div class="card" style="width: 40rem;">
    <div class="card-body">
      <h5 class="card-title">{{ car.title }}</h5>
      <h6 class="card-subtitle mb-2 text-muted">
        <small>
          {{ car.created_at|date:"d E Y, H:i" }}
          От автора
          <a class="text-muted" href="{% url 'car:profile' car.owner.username %}">@{{ car.owner.username }}</a>
        </small>
      </h6>
      <p class="card-text">{{ car.make }} {{ car.model }} ({{ car.year }})</p>
      <p class="card-text">{{ car.description|truncatewords:10 }}</p>
      <a href="{% url 'car:car_detail' car.id %}" class="card-link">Читать полный текст</a>
      <a href="{% url 'car:car_detail' car.id %}" class="card-link text-muted">Комментарии ({{ car.comment_count }})</a>
    </div>
  </div>
</div>